apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: inventory-database
    app.openshift.io/vcs-ref: ocp-4.7
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-08-04 - 20:35:01 +0000
    app.quarkus.io/commit-id: 277cea07dc580f9ff3f0a40fb619c190eba657cf
  creationTimestamp: "2022-08-04T20:36:27Z"
  generation: 2
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: inventory
  namespace: user3-cloudnativeapps
  resourceVersion: "3968345"
  uid: 5f739b68-2a8b-498a-887f-b358036dc458
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2022-08-04 - 20:35:01 +0000
        app.quarkus.io/commit-id: 277cea07dc580f9ff3f0a40fb619c190eba657cf
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: image-registry.openshift-image-registry.svc:5000/user3-cloudnativeapps/inventory@sha256:ccf3ef1ac62a70ae4138713b63108b6bc57d579efb799b04665b0bdfac17b098
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - inventory
      from:
        kind: ImageStreamTag
        name: inventory:1.0-SNAPSHOT
        namespace: user3-cloudnativeapps
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/user3-cloudnativeapps/inventory@sha256:ccf3ef1ac62a70ae4138713b63108b6bc57d579efb799b04665b0bdfac17b098
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-04T20:36:32Z"
    lastUpdateTime: "2022-08-04T20:36:43Z"
    message: replication controller "inventory-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-08-08T14:24:30Z"
    lastUpdateTime: "2022-08-08T14:24:30Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
