apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: inventory,catalog-database
    app.openshift.io/vcs-ref: ocp-4.7
    app.openshift.io/vcs-uri: https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-labs.git
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-08-04T20:37:53Z"
  generation: 2
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/part-of: catalog
    app.openshift.io/runtime: rh-spring-boot
  name: catalog
  namespace: user3-cloudnativeapps
  resourceVersion: "2685966"
  uid: 0effc644-0852-480e-b905-b8900c882d3b
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: catalog
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: catalog
    spec:
      containers:
      - env:
        - name: JAVA_OPTS_APPEND
          value: -Dspring.profiles.active=openshift
        image: image-registry.openshift-image-registry.svc:5000/user3-cloudnativeapps/catalog@sha256:88fd8cfe8bacbd0ebeadaef157cf2b8cff8ccaaecc85fd5bb3cf609090cefe00
        imagePullPolicy: Always
        name: catalog
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - catalog
      from:
        kind: ImageStreamTag
        name: catalog:latest
        namespace: user3-cloudnativeapps
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/user3-cloudnativeapps/catalog@sha256:88fd8cfe8bacbd0ebeadaef157cf2b8cff8ccaaecc85fd5bb3cf609090cefe00
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-04T20:37:57Z"
    lastUpdateTime: "2022-08-04T20:38:02Z"
    message: replication controller "catalog-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-08-05T19:02:25Z"
    lastUpdateTime: "2022-08-05T19:02:25Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
