apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-pv-claim
  labels:
    app: order
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd     
  resources:
    requests:
      storage: 5Gi
