apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: inventory
  namespace: user3-cloudnativeapps
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: inventory
    weight: 100
  wildcardPolicy: None
