apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-08-04T20:37:54Z"
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/instance: catalog
  name: catalog
  namespace: user3-cloudnativeapps
  resourceVersion: "2308299"
  uid: a2cbb117-8ceb-42cb-aea9-2f6c046ad87c
spec:
  host: catalog-user3-cloudnativeapps.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2022-08-04T20:37:54Z"
      status: "True"
      type: Admitted
    host: catalog-user3-cloudnativeapps.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
    routerCanonicalHostname: router-default.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
    routerName: default
    wildcardPolicy: None
