apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-08-04T21:22:34Z"
  labels:
    app.kubernetes.io/component: coolstore-ui
    app.kubernetes.io/instance: coolstore-ui
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime: nodejs
    project: coolstore-ui
    provider: nodeshift
    version: 1.0.0
  name: coolstore-ui
  namespace: user3-cloudnativeapps
  resourceVersion: "2435680"
  uid: 76442d40-fff1-4acb-a330-4a6abbe22c3f
spec:
  host: coolstore-ui-user3-cloudnativeapps.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
  port:
    targetPort: http
  to:
    kind: Service
    name: coolstore-ui
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2022-08-04T21:22:34Z"
      status: "True"
      type: Admitted
    host: coolstore-ui-user3-cloudnativeapps.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
    routerCanonicalHostname: router-default.apps.cluster-pjm25.pjm25.sandbox45.opentlc.com
    routerName: default
    wildcardPolicy: None
