apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/instance: catalog
  name: catalog
  namespace: user3-cloudnativeapps
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
