apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2022-08-04T20:55:38Z"
  labels:
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: strimzi-my-cluster
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-zookeeper
  name: my-cluster-zookeeper-nodes
  namespace: user3-cloudnativeapps
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta2
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: my-cluster
    uid: 77fd94c9-b45a-4b7e-9712-19e5aa26b763
  resourceVersion: "2359385"
  uid: 25b024d2-e99c-42af-b1aa-8c001dfdc18d
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-clustering
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  publishNotReadyAddresses: true
  selector:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
