apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-08-04T20:37:59Z"
  labels:
    app: datagrid-service
    app.kubernetes.io/component: datagrid-service
    app.kubernetes.io/instance: datagrid-service
  name: datagrid-service
  namespace: user3-cloudnativeapps
  resourceVersion: "2308570"
  uid: 365baa93-24ee-4ea7-a1c7-778c35e9276c
spec:
  clusterIP: 172.30.129.218
  clusterIPs:
  - 172.30.129.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 2157-tcp
    port: 2157
    protocol: TCP
    targetPort: 2157
  - name: 7800-tcp
    port: 7800
    protocol: TCP
    targetPort: 7800
  - name: 7900-tcp
    port: 7900
    protocol: TCP
    targetPort: 7900
  - name: 11221-tcp
    port: 11221
    protocol: TCP
    targetPort: 11221
  - name: 11222-tcp
    port: 11222
    protocol: TCP
    targetPort: 11222
  - name: 46655-tcp
    port: 46655
    protocol: TCP
    targetPort: 46655
  - name: 57600-tcp
    port: 57600
    protocol: TCP
    targetPort: 57600
  selector:
    deploymentconfig: datagrid-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
