apiVersion: v1
kind: Service
metadata:
  annotations:
    nodeshift/git-branch: ocp-4.10
    nodeshift/git-commit: bd1b49c6f063ef4072579378fa23566ed857dc74
  creationTimestamp: "2022-08-04T21:22:34Z"
  labels:
    app.kubernetes.io/component: coolstore-ui
    app.kubernetes.io/instance: coolstore-ui
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime: nodejs
    project: coolstore-ui
    provider: nodeshift
    version: 1.0.0
  name: coolstore-ui
  namespace: user3-cloudnativeapps
  resourceVersion: "2435650"
  uid: c7742d05-ac6b-4899-9c8f-6b8c0c5c525b
spec:
  clusterIP: 172.30.28.210
  clusterIPs:
  - 172.30.28.210
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    project: coolstore-ui
    provider: nodeshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
