apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: inventory
  namespace: user3-cloudnativeapps
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
