apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-08-04 - 21:06:30 +0000
    app.quarkus.io/commit-id: 277cea07dc580f9ff3f0a40fb619c190eba657cf
  creationTimestamp: "2022-08-04T21:07:54Z"
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: cart
  namespace: user3-cloudnativeapps
  resourceVersion: "2394455"
  uid: 47ba3b49-8106-465e-bbd4-bf6242114ebe
spec:
  clusterIP: 172.30.157.251
  clusterIPs:
  - 172.30.157.251
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
