apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-08-04T20:34:27Z"
  labels:
    app: inventory-database
    app.kubernetes.io/component: inventory-database
    app.kubernetes.io/instance: inventory-database
  name: inventory-database
  namespace: user3-cloudnativeapps
  resourceVersion: "2298401"
  uid: 6f03609f-8bdd-4a62-95d2-62b7feec80f8
spec:
  clusterIP: 172.30.131.130
  clusterIPs:
  - 172.30.131.130
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deploymentconfig: inventory-database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
