apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-08-04T20:37:53Z"
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/instance: catalog
  name: catalog
  namespace: user3-cloudnativeapps
  resourceVersion: "2308245"
  uid: c18b1fd2-3397-41f6-9687-3e19a5b84b0b
spec:
  clusterIP: 172.30.165.218
  clusterIPs:
  - 172.30.165.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deploymentconfig: catalog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
