apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-08-04T20:55:38Z"
  labels:
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: strimzi-my-cluster
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-zookeeper-client
  name: my-cluster-zookeeper-client
  namespace: user3-cloudnativeapps
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta2
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: my-cluster
    uid: 77fd94c9-b45a-4b7e-9712-19e5aa26b763
  resourceVersion: "2359383"
  uid: 122c8d6a-990e-4da5-85e3-d5c57e2cb5ae
spec:
  clusterIP: 172.30.164.99
  clusterIPs:
  - 172.30.164.99
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
