apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-08-04 - 21:32:34 +0000
    app.quarkus.io/commit-id: bd1b49c6f063ef4072579378fa23566ed857dc74
  creationTimestamp: "2022-08-04T21:33:42Z"
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order
  namespace: user3-cloudnativeapps
  resourceVersion: "2467221"
  uid: fad6455c-628c-4054-8f1b-cdf913a2acd2
spec:
  clusterIP: 172.30.179.16
  clusterIPs:
  - 172.30.179.16
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
